### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by vincethepro** [ShareX/ShareX_Firefox#1]
Hello, the extension does not work one single bit it does nothing. I was last updated 7 years ago

**Comment by Jaex** [comment]
I don't know why but Firefox broken it. They fixed it in Firefox nightly builds:

![](https://jaex.getsharex.com/2023/07/firefox_8S3zhjjG1H.png)

**Comment by vincethepro** [comment]
Alright thanks for letting me know let me try switching

**Comment by vincethepro** [comment]
Yep it works thanks

**Comment by Jaex** [comment]
Removing and reinstalling ShareX Firefox addon worked somehow.
