### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by CryShana** [ShareX/ShareX_Firefox#2]
I am using the latest stable Firefox release, **121.0 (64-bit)** and **ShareX 2.0.0 extension** - the extension is no longer showing the context menu item on any site anymore. When clicking on "Extensions" button on any site, it shows this:

![THvXfJZgbP](https://github.com/ShareX/ShareX_Firefox/assets/951230/98c593b0-b1dc-4956-8ba5-1df94d3263fb)

However in the Extensions settings it has all the permissions:

![firefox_Uj0eDBJSug](https://github.com/ShareX/ShareX_Firefox/assets/951230/b9ca4144-39b0-4d84-8041-e28912c2d53a)

This happens on two different PCs for same Firefox version, and I tried reinstalling the extension twice too and it does not change anything.

**Comment by Jaex** [comment]
https://chat.mozilla.org/#/room/%23addons:mozilla.org

![](https://jaex.getsharex.com/2023/12/chrome_IxT2nE6nbn.png)

:(

**Comment by CryShana** [comment]
It seems that the problem is now fixed with 2.0.1
